version: "3.1"

services:
  diudara-be:
    build:
      context: .
      dockerfile: ./app.Dockerfile
    container_name: diudara-be
    restart: always
    ports:
      - 8020:3000
    environment:
      - APP_ENV
      - APP_PORT
      - APP_HOST
      - DATABASE_URL
    networks:
      app-net: {}
    volumes:
      - ./keys:/app/keys

networks:
  app-net:
    external: true
    name: 'diudara-net'